// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.19.1
// source: follow.sql

package repository

import (
	"context"
)

const createFollows = `-- name: CreateFollows :one
INSERT INTO
  follows (to_user_id, from_user_id)
VALUES
($1, $2) RETURNING to_user_id, from_user_id, create_at
`

type CreateFollowsParams struct {
	ToUserID   string `json:"to_user_id"`
	FromUserID string `json:"from_user_id"`
}

func (q *Queries) CreateFollows(ctx context.Context, arg CreateFollowsParams) (Follow, error) {
	row := q.db.QueryRowContext(ctx, createFollows, arg.ToUserID, arg.FromUserID)
	var i Follow
	err := row.Scan(&i.ToUserID, &i.FromUserID, &i.CreateAt)
	return i, err
}

const deleteFollows = `-- name: DeleteFollows :exec
DELETE FROM
  follows
WHERE
  to_user_id = $1
  AND from_user_id = $2
`

type DeleteFollowsParams struct {
	ToUserID   string `json:"to_user_id"`
	FromUserID string `json:"from_user_id"`
}

func (q *Queries) DeleteFollows(ctx context.Context, arg DeleteFollowsParams) error {
	_, err := q.db.ExecContext(ctx, deleteFollows, arg.ToUserID, arg.FromUserID)
	return err
}

const listFollowsByToUserID = `-- name: ListFollowsByToUserID :many
SELECT
  to_user_id, from_user_id, create_at
FROM
  follows
WHERE
  to_user_id = $1
`

func (q *Queries) ListFollowsByToUserID(ctx context.Context, toUserID string) ([]Follow, error) {
	rows, err := q.db.QueryContext(ctx, listFollowsByToUserID, toUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Follow{}
	for rows.Next() {
		var i Follow
		if err := rows.Scan(&i.ToUserID, &i.FromUserID, &i.CreateAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
