// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.19.1

package repository

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Account struct {
	UserID          string         `json:"user_id"`
	Username        string         `json:"username"`
	Icon            sql.NullString `json:"icon"`
	ExplanatoryText sql.NullString `json:"explanatory_text"`
	LocateID        int32          `json:"locate_id"`
	Rate            int32          `json:"rate"`
	HashedPassword  sql.NullString `json:"hashed_password"`
	Email           string         `json:"email"`
	CreateAt        time.Time      `json:"create_at"`
	ShowLocate      bool           `json:"show_locate"`
	ShowRate        bool           `json:"show_rate"`
	UpdateAt        time.Time      `json:"update_at"`
	IsDelete        bool           `json:"is_delete"`
}

type AccountFramework struct {
	UserID      string `json:"user_id"`
	FrameworkID int32  `json:"framework_id"`
}

type AccountPastWork struct {
	Opus   int32  `json:"opus"`
	UserID string `json:"user_id"`
}

type AccountTag struct {
	UserID    string `json:"user_id"`
	TechTagID int32  `json:"tech_tag_id"`
}

type Award struct {
	AwardID int32  `json:"award_id"`
	Name    string `json:"name"`
}

type Bookmark struct {
	HackathonID int32     `json:"hackathon_id"`
	UserID      string    `json:"user_id"`
	CreateAt    time.Time `json:"create_at"`
	IsDelete    bool      `json:"is_delete"`
}

type Follow struct {
	ToUserID   string    `json:"to_user_id"`
	FromUserID string    `json:"from_user_id"`
	CreateAt   time.Time `json:"create_at"`
}

type Framework struct {
	FrameworkID int32  `json:"framework_id"`
	TechTagID   int32  `json:"tech_tag_id"`
	Framework   string `json:"framework"`
}

type Hackathon struct {
	HackathonID int32          `json:"hackathon_id"`
	Name        string         `json:"name"`
	Icon        sql.NullString `json:"icon"`
	Description string         `json:"description"`
	Link        string         `json:"link"`
	Expired     time.Time      `json:"expired"`
	StartDate   time.Time      `json:"start_date"`
	Term        int32          `json:"term"`
}

type HackathonStatusTag struct {
	HackathonID int32 `json:"hackathon_id"`
	StatusID    int32 `json:"status_id"`
}

type HackathonsDatum struct {
	Opus        int32 `json:"opus"`
	AwardID     int32 `json:"award_id"`
	HackathonID int32 `json:"hackathon_id"`
}

type Locate struct {
	LocateID int32  `json:"locate_id"`
	Name     string `json:"name"`
}

type PastWork struct {
	Opus            int32     `json:"opus"`
	Name            string    `json:"name"`
	ThumbnailImage  []byte    `json:"thumbnail_image"`
	ExplanatoryText string    `json:"explanatory_text"`
	CreateAt        time.Time `json:"create_at"`
	IsDelete        bool      `json:"is_delete"`
}

type PastWorkFramework struct {
	Opus        int32 `json:"opus"`
	FrameworkID int32 `json:"framework_id"`
}

type PastWorkTag struct {
	Opus      int32 `json:"opus"`
	TechTagID int32 `json:"tech_tag_id"`
}

type RateEntry struct {
	UserID   string    `json:"user_id"`
	Rate     int32     `json:"rate"`
	CreateAt time.Time `json:"create_at"`
}

type Room struct {
	RoomID      uuid.UUID `json:"room_id"`
	HackathonID int32     `json:"hackathon_id"`
	Title       string    `json:"title"`
	Description string    `json:"description"`
	MemberLimit int32     `json:"member_limit"`
	CreateAt    time.Time `json:"create_at"`
	IsDelete    bool      `json:"is_delete"`
}

type RoomsAccount struct {
	UserID   string    `json:"user_id"`
	RoomID   uuid.UUID `json:"room_id"`
	IsOwner  bool      `json:"is_owner"`
	CreateAt time.Time `json:"create_at"`
}

type StatusTag struct {
	StatusID int32  `json:"status_id"`
	Status   string `json:"status"`
}

type TechTag struct {
	TechTagID int32  `json:"tech_tag_id"`
	Language  string `json:"language"`
}
