
// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.19.1
// source: past_work_tags.sql

package repository

import (
	"context"
)

const createPastWorkTags = `-- name: CreatePastWorkTags :one
INSERT INTO past_work_tags (opus, tech_tag_id)
VALUES($1, $2)
RETURNING opus, tech_tag_id
`

type CreatePastWorkTagsParams struct {
	Opus      int32 `json:"opus"`
	TechTagID int32 `json:"tech_tag_id"`
}

func (q *Queries) CreatePastWorkTags(ctx context.Context, arg CreatePastWorkTagsParams) (PastWorkTag, error) {
	row := q.db.QueryRowContext(ctx, createPastWorkTags, arg.Opus, arg.TechTagID)
	var i PastWorkTag
	err := row.Scan(&i.Opus, &i.TechTagID)
	return i, err
}

const deletePastWorkTagsByOpus = `-- name: DeletePastWorkTagsByOpus :exec
DELETE FROM past_work_tags
WHERE opus = $1
`

func (q *Queries) DeletePastWorkTagsByOpus(ctx context.Context, opus int32) error {
	_, err := q.db.ExecContext(ctx, deletePastWorkTagsByOpus, opus)
	return err
}

const listPastWorkTagsByOpus = `-- name: ListPastWorkTagsByOpus :many
SELECT opus, tech_tag_id
FROM past_work_tags
WHERE opus = $1
`

func (q *Queries) ListPastWorkTagsByOpus(ctx context.Context, opus int32) ([]PastWorkTag, error) {
	rows, err := q.db.QueryContext(ctx, listPastWorkTagsByOpus, opus)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PastWorkTag{}
	for rows.Next() {
		var i PastWorkTag
		if err := rows.Scan(&i.Opus, &i.TechTagID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
