// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.19.1

package repository

import (
	"context"
)

type Querier interface {
	CreateAccountFrameworks(ctx context.Context, arg CreateAccountFrameworksParams) (AccountFramework, error)
	CreateAccountPastWorks(ctx context.Context, arg CreateAccountPastWorksParams) (AccountPastWork, error)
	CreateAccountTags(ctx context.Context, arg CreateAccountTagsParams) (AccountTag, error)
	CreateAccounts(ctx context.Context, arg CreateAccountsParams) (Account, error)
	CreateFollows(ctx context.Context, arg CreateFollowsParams) (Follow, error)
	CreateFrameworks(ctx context.Context, arg CreateFrameworksParams) (Framework, error)
	CreateHackathonStatusTags(ctx context.Context, arg CreateHackathonStatusTagsParams) (HackathonStatusTag, error)
	CreateHackathons(ctx context.Context, arg CreateHackathonsParams) (Hackathon, error)
	CreateLikes(ctx context.Context, arg CreateLikesParams) (Like, error)
	CreateLocates(ctx context.Context, name string) (Locate, error)
	CreatePastWorkFrameworks(ctx context.Context, arg CreatePastWorkFrameworksParams) (PastWorkFramework, error)
	CreatePastWorkTags(ctx context.Context, arg CreatePastWorkTagsParams) (PastWorkTag, error)
	CreatePastWorks(ctx context.Context, arg CreatePastWorksParams) (PastWork, error)
	CreateRateEntities(ctx context.Context, arg CreateRateEntitiesParams) (RateEntity, error)
	CreateRoles(ctx context.Context, role string) (Role, error)
	CreateRooms(ctx context.Context, arg CreateRoomsParams) (Room, error)
	CreateRoomsAccounts(ctx context.Context, arg CreateRoomsAccountsParams) (RoomsAccount, error)
	CreateStatusTags(ctx context.Context, status string) (StatusTag, error)
	CreateTechTags(ctx context.Context, language string) (TechTag, error)
	DeleteAccountFrameworkByUserID(ctx context.Context, accountID string) error
	DeleteAccountPastWorksByOpus(ctx context.Context, opus int32) error
	DeleteAccountTagsByUserID(ctx context.Context, accountID string) error
	DeleteAccounts(ctx context.Context, accountID string) (Account, error)
	DeleteFollows(ctx context.Context, arg DeleteFollowsParams) error
	DeleteFrameworksByID(ctx context.Context, frameworkID int32) error
	DeleteHackathonByID(ctx context.Context, hackathonID int32) error
	DeleteHackathonStatusTagsByID(ctx context.Context, hackathonID int32) error
	DeleteLikesByID(ctx context.Context, arg DeleteLikesByIDParams) (Like, error)
	DeletePastWorkFrameworksByOpus(ctx context.Context, opus int32) error
	DeletePastWorkTagsByOpus(ctx context.Context, opus int32) error
	DeletePastWorksByID(ctx context.Context, arg DeletePastWorksByIDParams) (PastWork, error)
	DeleteRoomsAccountsByID(ctx context.Context, arg DeleteRoomsAccountsByIDParams) error
	DeleteRoomsByID(ctx context.Context, roomID string) (Room, error)
	DeleteStatusTagsByStatusID(ctx context.Context, statusID int32) error
	DeleteTechTagsByID(ctx context.Context, techTagID int32) error
	GetAccountsByEmail(ctx context.Context, email string) (Account, error)
	GetAccountsByID(ctx context.Context, accountID string) (Account, error)
	GetFrameworksByID(ctx context.Context, frameworkID int32) (Framework, error)
	GetHackathonByID(ctx context.Context, hackathonID int32) (Hackathon, error)
	GetLikeStatusByID(ctx context.Context, arg GetLikeStatusByIDParams) (Like, error)
	GetListCountByOpus(ctx context.Context, opus int32) (int64, error)
	GetLocatesByID(ctx context.Context, locateID int32) (Locate, error)
	GetPastWorksByOpus(ctx context.Context, opus int32) (PastWork, error)
	GetRolesByID(ctx context.Context, roleID int32) (Role, error)
	GetRoomsAccountsByID(ctx context.Context, roomID string) ([]GetRoomsAccountsByIDRow, error)
	GetRoomsByID(ctx context.Context, roomID string) (Room, error)
	GetStatusTagsByHackathonID(ctx context.Context, hackathonID int32) (StatusTag, error)
	GetStatusTagsByTag(ctx context.Context, statusID int32) (StatusTag, error)
	GetTechTagsByID(ctx context.Context, techTagID int32) (TechTag, error)
	ListAccountFrameworksByUserID(ctx context.Context, accountID string) ([]ListAccountFrameworksByUserIDRow, error)
	ListAccountPastWorksByOpus(ctx context.Context, opus int32) ([]AccountPastWork, error)
	ListAccountTagsByUserID(ctx context.Context, accountID string) ([]ListAccountTagsByUserIDRow, error)
	ListAccounts(ctx context.Context, arg ListAccountsParams) ([]Account, error)
	ListFollowsByFromUserID(ctx context.Context, fromAccountID string) ([]Follow, error)
	ListFollowsByToUserID(ctx context.Context, toAccountID string) ([]Follow, error)
	ListFrameworks(ctx context.Context) ([]Framework, error)
	ListHackathonStatusTagsByID(ctx context.Context, hackathonID int32) ([]HackathonStatusTag, error)
	ListHackathons(ctx context.Context, arg ListHackathonsParams) ([]Hackathon, error)
	ListLikesByID(ctx context.Context, accountID string) ([]Like, error)
	ListLocates(ctx context.Context) ([]Locate, error)
	ListPastWorkFrameworksByOpus(ctx context.Context, opus int32) ([]PastWorkFramework, error)
	ListPastWorkTagsByOpus(ctx context.Context, opus int32) ([]PastWorkTag, error)
	ListPastWorks(ctx context.Context, arg ListPastWorksParams) ([]ListPastWorksRow, error)
	ListRateEntities(ctx context.Context, arg ListRateEntitiesParams) ([]RateEntity, error)
	ListRoles(ctx context.Context) ([]Role, error)
	ListRooms(ctx context.Context, arg ListRoomsParams) ([]Room, error)
	ListStatusTags(ctx context.Context) ([]StatusTag, error)
	ListTechTags(ctx context.Context) ([]TechTag, error)
	UpdateAccounts(ctx context.Context, arg UpdateAccountsParams) (Account, error)
	UpdateFrameworksByID(ctx context.Context, arg UpdateFrameworksByIDParams) (Framework, error)
	UpdatePastWorksByID(ctx context.Context, arg UpdatePastWorksByIDParams) (PastWork, error)
	UpdateRateByID(ctx context.Context, arg UpdateRateByIDParams) (Account, error)
	UpdateRoomsByID(ctx context.Context, arg UpdateRoomsByIDParams) (Room, error)
	UpdateTechTagsByID(ctx context.Context, arg UpdateTechTagsByIDParams) (TechTag, error)
}

var _ Querier = (*Queries)(nil)
