// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.19.1
// source: rate.sql

package repository

import (
	"context"
)

const createRateEntries = `-- name: CreateRateEntries :one
INSERT INTO rate_entries (user_id, rate)
VALUES($1, $2)
RETURNING user_id, rate, create_at
`

type CreateRateEntriesParams struct {
	UserID string `json:"user_id"`
	Rate   int32  `json:"rate"`
}

func (q *Queries) CreateRateEntries(ctx context.Context, arg CreateRateEntriesParams) (RateEntry, error) {
	row := q.db.QueryRowContext(ctx, createRateEntries, arg.UserID, arg.Rate)
	var i RateEntry
	err := row.Scan(&i.UserID, &i.Rate, &i.CreateAt)
	return i, err
}

const listRateEntries = `-- name: ListRateEntries :many
SELECT user_id, rate, create_at
FROM rate_entries
WHERE user_id = $1
LIMIT $2 OFFSET $3
`

type ListRateEntriesParams struct {
	UserID string `json:"user_id"`
	Limit  int32  `json:"limit"`
	Offset int32  `json:"offset"`
}

func (q *Queries) ListRateEntries(ctx context.Context, arg ListRateEntriesParams) ([]RateEntry, error) {
	rows, err := q.db.QueryContext(ctx, listRateEntries, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RateEntry{}
	for rows.Next() {
		var i RateEntry
		if err := rows.Scan(&i.UserID, &i.Rate, &i.CreateAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
