// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.19.1
// source: rate.sql

package repository

import (
	"context"
)

const createRateEntries = `-- name: CreateRateEntries :one
INSERT INTO rate_entities (account_id, rate)
VALUES($1, $2)
RETURNING account_id, rate, create_at
`

type CreateRateEntriesParams struct {
	AccountID string `json:"account_id"`
	Rate      int32  `json:"rate"`
}

func (q *Queries) CreateRateEntries(ctx context.Context, arg CreateRateEntriesParams) (RateEntity, error) {
	row := q.db.QueryRowContext(ctx, createRateEntries, arg.AccountID, arg.Rate)
	var i RateEntity
	err := row.Scan(&i.AccountID, &i.Rate, &i.CreateAt)
	return i, err
}

const listRateEntries = `-- name: ListRateEntries :many
SELECT account_id, rate, create_at
FROM rate_entities
WHERE account_id = $1
LIMIT $2 OFFSET $3
`

type ListRateEntriesParams struct {
	AccountID string `json:"account_id"`
	Limit     int32  `json:"limit"`
	Offset    int32  `json:"offset"`
}

func (q *Queries) ListRateEntries(ctx context.Context, arg ListRateEntriesParams) ([]RateEntity, error) {
	rows, err := q.db.QueryContext(ctx, listRateEntries, arg.AccountID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RateEntity{}
	for rows.Next() {
		var i RateEntity
		if err := rows.Scan(&i.AccountID, &i.Rate, &i.CreateAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
