// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.19.1
// source: room.sql

package repository

import (
	"context"

	"github.com/google/uuid"
)

const createRooms = `-- name: CreateRooms :one
INSERT INTO rooms (
        room_id,
        hackathon_id,
        title,
        description,
        member_limit,
        is_delete
    )
VALUES($1, $2, $3, $4, $5, $6)
RETURNING room_id, hackathon_id, title, description, member_limit, include_rate, create_at, update_at, is_delete
`

type CreateRoomsParams struct {
	RoomID      uuid.UUID `json:"room_id"`
	HackathonID int32     `json:"hackathon_id"`
	Title       string    `json:"title"`
	Description string    `json:"description"`
	MemberLimit int32     `json:"member_limit"`
	IsDelete    bool      `json:"is_delete"`
}

func (q *Queries) CreateRooms(ctx context.Context, arg CreateRoomsParams) (Room, error) {
	row := q.db.QueryRowContext(ctx, createRooms,
		arg.RoomID,
		arg.HackathonID,
		arg.Title,
		arg.Description,
		arg.MemberLimit,
		arg.IsDelete,
	)
	var i Room
	err := row.Scan(
		&i.RoomID,
		&i.HackathonID,
		&i.Title,
		&i.Description,
		&i.MemberLimit,
		&i.IncludeRate,
		&i.CreateAt,
		&i.UpdateAt,
		&i.IsDelete,
	)
	return i, err
}

const deleteRoomsByID = `-- name: DeleteRoomsByID :one
UPDATE rooms
SET is_delete = true
WHERE room_id = $1
RETURNING room_id, hackathon_id, title, description, member_limit, include_rate, create_at, update_at, is_delete
`

func (q *Queries) DeleteRoomsByID(ctx context.Context, roomID uuid.UUID) (Room, error) {
	row := q.db.QueryRowContext(ctx, deleteRoomsByID, roomID)
	var i Room
	err := row.Scan(
		&i.RoomID,
		&i.HackathonID,
		&i.Title,
		&i.Description,
		&i.MemberLimit,
		&i.IncludeRate,
		&i.CreateAt,
		&i.UpdateAt,
		&i.IsDelete,
	)
	return i, err
}

const getRoomsByID = `-- name: GetRoomsByID :one
SELECT room_id, hackathon_id, title, description, member_limit, include_rate, create_at, update_at, is_delete
FROM rooms
WHERE room_id = $1
`

func (q *Queries) GetRoomsByID(ctx context.Context, roomID uuid.UUID) (Room, error) {
	row := q.db.QueryRowContext(ctx, getRoomsByID, roomID)
	var i Room
	err := row.Scan(
		&i.RoomID,
		&i.HackathonID,
		&i.Title,
		&i.Description,
		&i.MemberLimit,
		&i.IncludeRate,
		&i.CreateAt,
		&i.UpdateAt,
		&i.IsDelete,
	)
	return i, err
}

const listRooms = `-- name: ListRooms :many
SELECT room_id, hackathon_id, title, description, member_limit, include_rate, create_at, update_at, is_delete
FROM rooms
WHERE member_limit > (
        SELECT count(*)
        FROM rooms_accounts
        WHERE rooms_accounts.room_id = rooms.room_id
    )
    AND is_delete = false
LIMIT $1 OFFSET $2
`

type ListRoomsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListRooms(ctx context.Context, arg ListRoomsParams) ([]Room, error) {
	rows, err := q.db.QueryContext(ctx, listRooms, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Room{}
	for rows.Next() {
		var i Room
		if err := rows.Scan(
			&i.RoomID,
			&i.HackathonID,
			&i.Title,
			&i.Description,
			&i.MemberLimit,
			&i.IncludeRate,
			&i.CreateAt,
			&i.UpdateAt,
			&i.IsDelete,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRoomsByID = `-- name: UpdateRoomsByID :one
UPDATE rooms
SET hackathon_id = $1,
    title = $2,
    description = $3,
    member_limit = $4
WHERE room_id = $5
RETURNING room_id, hackathon_id, title, description, member_limit, include_rate, create_at, update_at, is_delete
`

type UpdateRoomsByIDParams struct {
	HackathonID int32     `json:"hackathon_id"`
	Title       string    `json:"title"`
	Description string    `json:"description"`
	MemberLimit int32     `json:"member_limit"`
	RoomID      uuid.UUID `json:"room_id"`
}

func (q *Queries) UpdateRoomsByID(ctx context.Context, arg UpdateRoomsByIDParams) (Room, error) {
	row := q.db.QueryRowContext(ctx, updateRoomsByID,
		arg.HackathonID,
		arg.Title,
		arg.Description,
		arg.MemberLimit,
		arg.RoomID,
	)
	var i Room
	err := row.Scan(
		&i.RoomID,
		&i.HackathonID,
		&i.Title,
		&i.Description,
		&i.MemberLimit,
		&i.IncludeRate,
		&i.CreateAt,
		&i.UpdateAt,
		&i.IsDelete,
	)
	return i, err
}
