// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0
// source: frameworks.sql

package db

import (
	"context"
)

const getFrameworks = `-- name: GetFrameworks :one
SELECT framework_id, tech_tag_id, framework FROM frameworks WHERE framework_id = $1
`

func (q *Queries) GetFrameworks(ctx context.Context, frameworkID int32) (Frameworks, error) {
	row := q.db.QueryRowContext(ctx, getFrameworks, frameworkID)
	var i Frameworks
	err := row.Scan(&i.FrameworkID, &i.TechTagID, &i.Framework)
	return i, err
}

const listFrameworks = `-- name: ListFrameworks :many
SELECT framework_id, tech_tag_id, framework FROM frameworks LIMIT $1
`

func (q *Queries) ListFrameworks(ctx context.Context, limit int32) ([]Frameworks, error) {
	rows, err := q.db.QueryContext(ctx, listFrameworks, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Frameworks{}
	for rows.Next() {
		var i Frameworks
		if err := rows.Scan(&i.FrameworkID, &i.TechTagID, &i.Framework); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
