// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0
// source: locate.sql

package db

import (
	"context"
)

const listLocates = `-- name: ListLocates :many
SELECT locate_id, name FROM locates
`

func (q *Queries) ListLocates(ctx context.Context) ([]Locates, error) {
	rows, err := q.db.QueryContext(ctx, listLocates)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Locates{}
	for rows.Next() {
		var i Locates
		if err := rows.Scan(&i.LocateID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
