// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0

package db

import (
	"time"

	"github.com/google/uuid"
)

type AccountPastWorks struct {
	Opus      int32 `json:"opus"`
	AccountID int32 `json:"account_id"`
}

type AccountTags struct {
	AccountID int32 `json:"account_id"`
	TechTagID int32 `json:"tech_tag_id"`
}

type Accounts struct {
	AccountID       int32  `json:"account_id"`
	UserID          int32  `json:"user_id"`
	Username        int32  `json:"username"`
	Icon            []byte `json:"icon"`
	ExplanatoryText string `json:"explanatory_text"`
	LocateID        int32  `json:"locate_id"`
	Rate            int32  `json:"rate"`
}

type Awards struct {
	AwardID int32  `json:"award_id"`
	Name    string `json:"name"`
}

type Bookmarks struct {
	HackathonID int32 `json:"hackathon_id"`
	AccountID   int32 `json:"account_id"`
}

type Follows struct {
	ToAccountID   int32 `json:"to_account_id"`
	FromAccountID int32 `json:"from_account_id"`
}

type HackathonStatusTags struct {
	HackathonID int32 `json:"hackathon_id"`
	StatusID    int32 `json:"status_id"`
}

type Hackathons struct {
	HackathonID int32     `json:"hackathon_id"`
	Name        string    `json:"name"`
	Icon        []byte    `json:"icon"`
	Description string    `json:"description"`
	Expired     time.Time `json:"expired"`
	Available   bool      `json:"available"`
	StartDate   time.Time `json:"start_Date"`
	Term        int32     `json:"term"`
	IsOnline    bool      `json:"is_Online"`
}

type HackathonsData struct {
	Opus        int32 `json:"opus"`
	AwardID     int32 `json:"award_id"`
	HackathonID int32 `json:"hackathon_id"`
}

type Locates struct {
	LocateID int32  `json:"locate_id"`
	Name     string `json:"name"`
}

type PastWorkTags struct {
	Opus      int32 `json:"opus"`
	TechTagID int32 `json:"tech_tag_id"`
}

type PastWorks struct {
	Opus            int32  `json:"opus"`
	ThumbnailImage  []byte `json:"thumbnail_image"`
	ExplanatoryText string `json:"explanatory_text"`
}

type RateEntries struct {
	AccountID int32     `json:"account_id"`
	Rate      int32     `json:"rate"`
	CreateAt  time.Time `json:"create_at"`
}

type Rooms struct {
	RoomID      uuid.UUID `json:"room_id"`
	HackathonID int32     `json:"hackathon_id"`
	Title       string    `json:"title"`
	Description string    `json:"description"`
	Limit       int32     `json:"limit"`
	Status      bool      `json:"status"`
}

type RoomsAccounts struct {
	RoomID    uuid.UUID `json:"room_id"`
	AccountID int32     `json:"account_id"`
}

type RoomsTechTags struct {
	RoomID    uuid.UUID `json:"room_id"`
	TechTagID int32     `json:"tech_tag_id"`
}

type StatusTags struct {
	StatusID int32  `json:"status_id"`
	Status   string `json:"status"`
}

type TechTags struct {
	TechTagID int32  `json:"tech_tag_id"`
	TechTag   string `json:"tech_tag"`
}

type Users struct {
	UserID         int32     `json:"user_id"`
	HashedPassword string    `json:"hashed_password"`
	Email          string    `json:"email"`
	CreateAt       time.Time `json:"create_at"`
}
