// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0
// source: rooms_frameworks.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createRoomsFramework = `-- name: CreateRoomsFramework :one
INSERT INTO rooms_frameworks (
    room_id,
    framework_id
)VALUES(
    $1,$2
)RETURNING room_id, framework_id
`

type CreateRoomsFrameworkParams struct {
	RoomID      uuid.UUID `json:"room_id"`
	FrameworkID int32     `json:"framework_id"`
}

func (q *Queries) CreateRoomsFramework(ctx context.Context, arg CreateRoomsFrameworkParams) (RoomsFrameworks, error) {
	row := q.db.QueryRowContext(ctx, createRoomsFramework, arg.RoomID, arg.FrameworkID)
	var i RoomsFrameworks
	err := row.Scan(&i.RoomID, &i.FrameworkID)
	return i, err
}

const listRoomsFrameworks = `-- name: ListRoomsFrameworks :many
SELECT 
    frameworks.framework_id,
    frameworks.tech_tag_id,
    frameworks.framework
FROM 
    rooms_frameworks
LEFT OUTER JOIN 
    frameworks 
ON 
    rooms_frameworks.framework_id = frameworks.framework_id 
WHERE 
    rooms_frameworks.room_id = $1
`

type ListRoomsFrameworksRow struct {
	FrameworkID sql.NullInt32  `json:"framework_id"`
	TechTagID   sql.NullInt32  `json:"tech_tag_id"`
	Framework   sql.NullString `json:"framework"`
}

func (q *Queries) ListRoomsFrameworks(ctx context.Context, roomID uuid.UUID) ([]ListRoomsFrameworksRow, error) {
	rows, err := q.db.QueryContext(ctx, listRoomsFrameworks, roomID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRoomsFrameworksRow{}
	for rows.Next() {
		var i ListRoomsFrameworksRow
		if err := rows.Scan(&i.FrameworkID, &i.TechTagID, &i.Framework); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
