// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0
// source: statusTags.sql

package db

import (
	"context"
)

const listStatusTags = `-- name: ListStatusTags :many
SELECT status_id, status
FROM status_tags
where status_id = $1
`

func (q *Queries) ListStatusTags(ctx context.Context, statusID int32) ([]StatusTags, error) {
	rows, err := q.db.QueryContext(ctx, listStatusTags, statusID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []StatusTags{}
	for rows.Next() {
		var i StatusTags
		if err := rows.Scan(&i.StatusID, &i.Status); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
