// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.19.0
// source: tech_tags.sql

package db

import (
	"context"
)

const getTechTagByID = `-- name: GetTechTagByID :one
SELECT tech_tag_id, language FROM tech_tags WHERE tech_tag_id = $1
`

func (q *Queries) GetTechTagByID(ctx context.Context, techTagID int32) (TechTags, error) {
	row := q.db.QueryRowContext(ctx, getTechTagByID, techTagID)
	var i TechTags
	err := row.Scan(&i.TechTagID, &i.Language)
	return i, err
}

const listTechTag = `-- name: ListTechTag :many
SELECT tech_tag_id, language FROM tech_tags
`

func (q *Queries) ListTechTag(ctx context.Context) ([]TechTags, error) {
	rows, err := q.db.QueryContext(ctx, listTechTag)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TechTags{}
	for rows.Next() {
		var i TechTags
		if err := rows.Scan(&i.TechTagID, &i.Language); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
