// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0
// source: user.sql

package db

import (
	"context"
)

const createUsers = `-- name: CreateUsers :one
INSERT INTO users (
    hashed_password,
    email
)VALUES(
    $1,$2
)RETURNING user_id, hashed_password, email, create_at
`

type CreateUsersParams struct {
	HashedPassword string `json:"hashed_password"`
	Email          string `json:"email"`
}

func (q *Queries) CreateUsers(ctx context.Context, arg CreateUsersParams) (Users, error) {
	row := q.db.QueryRowContext(ctx, createUsers, arg.HashedPassword, arg.Email)
	var i Users
	err := row.Scan(
		&i.UserID,
		&i.HashedPassword,
		&i.Email,
		&i.CreateAt,
	)
	return i, err
}
