// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.22.0
// source: hackathon.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createHackathons = `-- name: CreateHackathons :one
INSERT INTO
  hackathons (
    name,
    icon,
    description,
    link,
    expired,
    start_date,
    term
  )
VALUES
($1, $2, $3, $4, $5, $6, $7) RETURNING hackathon_id, name, icon, description, link, expired, start_date, term
`

type CreateHackathonsParams struct {
	Name        string      `json:"name"`
	Icon        pgtype.Text `json:"icon"`
	Description string      `json:"description"`
	Link        string      `json:"link"`
	Expired     pgtype.Date `json:"expired"`
	StartDate   pgtype.Date `json:"start_date"`
	Term        int32       `json:"term"`
}

func (q *Queries) CreateHackathons(ctx context.Context, arg CreateHackathonsParams) (Hackathon, error) {
	row := q.db.QueryRow(ctx, createHackathons,
		arg.Name,
		arg.Icon,
		arg.Description,
		arg.Link,
		arg.Expired,
		arg.StartDate,
		arg.Term,
	)
	var i Hackathon
	err := row.Scan(
		&i.HackathonID,
		&i.Name,
		&i.Icon,
		&i.Description,
		&i.Link,
		&i.Expired,
		&i.StartDate,
		&i.Term,
	)
	return i, err
}

const deleteHackathonByID = `-- name: DeleteHackathonByID :exec
DELETE FROM
  hackathons
WHERE
  hackathon_id = $1
`

func (q *Queries) DeleteHackathonByID(ctx context.Context, hackathonID int32) error {
	_, err := q.db.Exec(ctx, deleteHackathonByID, hackathonID)
	return err
}

const getHackathonByID = `-- name: GetHackathonByID :one
SELECT
  hackathon_id, name, icon, description, link, expired, start_date, term
FROM
  hackathons
WHERE
  hackathon_id = $1
`

func (q *Queries) GetHackathonByID(ctx context.Context, hackathonID int32) (Hackathon, error) {
	row := q.db.QueryRow(ctx, getHackathonByID, hackathonID)
	var i Hackathon
	err := row.Scan(
		&i.HackathonID,
		&i.Name,
		&i.Icon,
		&i.Description,
		&i.Link,
		&i.Expired,
		&i.StartDate,
		&i.Term,
	)
	return i, err
}

const listHackathons = `-- name: ListHackathons :many
SELECT
  hackathon_id, name, icon, description, link, expired, start_date, term
FROM
  hackathons
WHERE
  expired > $1
ORDER BY
  expired ASC
LIMIT
  $2 OFFSET $3
`

type ListHackathonsParams struct {
	Expired pgtype.Date `json:"expired"`
	Limit   int32       `json:"limit"`
	Offset  int32       `json:"offset"`
}

func (q *Queries) ListHackathons(ctx context.Context, arg ListHackathonsParams) ([]Hackathon, error) {
	rows, err := q.db.Query(ctx, listHackathons, arg.Expired, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Hackathon{}
	for rows.Next() {
		var i Hackathon
		if err := rows.Scan(
			&i.HackathonID,
			&i.Name,
			&i.Icon,
			&i.Description,
			&i.Link,
			&i.Expired,
			&i.StartDate,
			&i.Term,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
