// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.22.0

package repository

import (
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type Account struct {
	AccountID       string      `json:"account_id"`
	Username        string      `json:"username"`
	Icon            pgtype.Text `json:"icon"`
	ExplanatoryText pgtype.Text `json:"explanatory_text"`
	LocateID        int32       `json:"locate_id"`
	Rate            int32       `json:"rate"`
	Character       pgtype.Int4 `json:"character"`
	ShowLocate      bool        `json:"show_locate"`
	ShowRate        bool        `json:"show_rate"`
	CreateAt        time.Time   `json:"create_at"`
	UpdateAt        time.Time   `json:"update_at"`
	IsDelete        bool        `json:"is_delete"`
	Email           string      `json:"email"`
	TwitterLink     pgtype.Text `json:"twitter_link"`
	GithubLink      pgtype.Text `json:"github_link"`
	DiscordLink     pgtype.Text `json:"discord_link"`
}

type AccountFramework struct {
	AccountID   string `json:"account_id"`
	FrameworkID int32  `json:"framework_id"`
}

type AccountPastWork struct {
	Opus      int32  `json:"opus"`
	AccountID string `json:"account_id"`
}

type AccountTag struct {
	AccountID string `json:"account_id"`
	TechTagID int32  `json:"tech_tag_id"`
}

type AccountsAchievment struct {
	AccountID    string    `json:"account_id"`
	AchievmentID int32     `json:"achievment_id"`
	CreateAt     time.Time `json:"create_at"`
}

type Achievment struct {
	AchievmentID int32     `json:"achievment_id"`
	Achievment   string    `json:"achievment"`
	Description  string    `json:"description"`
	Icon         string    `json:"icon"`
	Conditions   string    `json:"conditions"`
	CreateAt     time.Time `json:"create_at"`
	IsDelete     bool      `json:"is_delete"`
}

type Award struct {
	AwardID int32  `json:"award_id"`
	Name    string `json:"name"`
	Icon    string `json:"icon"`
}

type AwardDatum struct {
	AwardDataID int32 `json:"award_data_id"`
	AwardID     int32 `json:"award_id"`
	HackathonID int32 `json:"hackathon_id"`
}

type Follow struct {
	ToAccountID   string    `json:"to_account_id"`
	FromAccountID string    `json:"from_account_id"`
	CreateAt      time.Time `json:"create_at"`
}

type Framework struct {
	FrameworkID int32  `json:"framework_id"`
	TechTagID   int32  `json:"tech_tag_id"`
	Framework   string `json:"framework"`
	Icon        string `json:"icon"`
}

type Hackathon struct {
	HackathonID int32       `json:"hackathon_id"`
	Name        string      `json:"name"`
	Icon        pgtype.Text `json:"icon"`
	Description string      `json:"description"`
	Link        string      `json:"link"`
	Expired     pgtype.Date `json:"expired"`
	StartDate   pgtype.Date `json:"start_date"`
	Term        int32       `json:"term"`
}

type HackathonStatusTag struct {
	HackathonID int32 `json:"hackathon_id"`
	StatusID    int32 `json:"status_id"`
}

type Like struct {
	Opus      int32     `json:"opus"`
	AccountID string    `json:"account_id"`
	CreateAt  time.Time `json:"create_at"`
	IsDelete  bool      `json:"is_delete"`
}

type Locate struct {
	LocateID int32  `json:"locate_id"`
	Name     string `json:"name"`
}

type PastWork struct {
	Opus            int32       `json:"opus"`
	Name            string      `json:"name"`
	ThumbnailImage  string      `json:"thumbnail_image"`
	ExplanatoryText string      `json:"explanatory_text"`
	AwardDataID     pgtype.Int4 `json:"award_data_id"`
	CreateAt        time.Time   `json:"create_at"`
	UpdateAt        time.Time   `json:"update_at"`
	IsDelete        bool        `json:"is_delete"`
}

type PastWorkFramework struct {
	Opus        int32 `json:"opus"`
	FrameworkID int32 `json:"framework_id"`
}

type PastWorkTag struct {
	Opus      int32 `json:"opus"`
	TechTagID int32 `json:"tech_tag_id"`
}

type RateEntity struct {
	AccountID string    `json:"account_id"`
	Rate      int32     `json:"rate"`
	CreateAt  time.Time `json:"create_at"`
}

type Role struct {
	RoleID int32  `json:"role_id"`
	Role   string `json:"role"`
}

type Room struct {
	RoomID      string      `json:"room_id"`
	HackathonID int32       `json:"hackathon_id"`
	Title       string      `json:"title"`
	Description string      `json:"description"`
	MemberLimit int32       `json:"member_limit"`
	IncludeRate bool        `json:"include_rate"`
	CreateAt    time.Time   `json:"create_at"`
	UpdateAt    time.Time   `json:"update_at"`
	IsDelete    bool        `json:"is_delete"`
	IsClosing   pgtype.Bool `json:"is_closing"`
}

type RoomChat struct {
	ChatID    string    `json:"chat_id"`
	RoomID    string    `json:"room_id"`
	AccountID string    `json:"account_id"`
	Message   string    `json:"message"`
	CreatedAt time.Time `json:"created_at"`
}

type RoomsAccount struct {
	RoomsAccountID int32     `json:"rooms_account_id"`
	AccountID      string    `json:"account_id"`
	RoomID         string    `json:"room_id"`
	IsOwner        bool      `json:"is_owner"`
	CreateAt       time.Time `json:"create_at"`
}

type RoomsAccountsRole struct {
	RoomsAccountID int32 `json:"rooms_account_id"`
	RoleID         int32 `json:"role_id"`
}

type StatusTag struct {
	StatusID int32  `json:"status_id"`
	Status   string `json:"status"`
}

type TechTag struct {
	TechTagID int32  `json:"tech_tag_id"`
	Language  string `json:"language"`
	Icon      string `json:"icon"`
}

type Tutor struct {
	TutorID     string      `json:"tutor_id"`
	Title       string      `json:"Title"`
	Description pgtype.Text `json:"description"`
	CreateAt    time.Time   `json:"create_at"`
	UpdateAt    time.Time   `json:"update_at"`
	IsDelete    bool        `json:"is_delete"`
}
