// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.22.0
// source: sqlc.status_tags.sql

package repository

import (
	"context"
)

const createStatusTags = `-- name: CreateStatusTags :one
INSERT INTO status_tags (status) VALUES ($1) RETURNING status_id, status
`

func (q *Queries) CreateStatusTags(ctx context.Context, status string) (StatusTag, error) {
	row := q.db.QueryRow(ctx, createStatusTags, status)
	var i StatusTag
	err := row.Scan(&i.StatusID, &i.Status)
	return i, err
}

const deleteStatusTagsByStatusID = `-- name: DeleteStatusTagsByStatusID :exec
DELETE FROM
    status_tags
WHERE status_id = $1
`

func (q *Queries) DeleteStatusTagsByStatusID(ctx context.Context, statusID int32) error {
	_, err := q.db.Exec(ctx, deleteStatusTagsByStatusID, statusID)
	return err
}

const getStatusTagsByTag = `-- name: GetStatusTagsByTag :one
SELECT status_id ,status
FROM status_tags
where status_id = $1
`

func (q *Queries) GetStatusTagsByTag(ctx context.Context, statusID int32) (StatusTag, error) {
	row := q.db.QueryRow(ctx, getStatusTagsByTag, statusID)
	var i StatusTag
	err := row.Scan(&i.StatusID, &i.Status)
	return i, err
}

const listStatusTags = `-- name: ListStatusTags :many
SELECT status_id, status
FROM status_tags
`

func (q *Queries) ListStatusTags(ctx context.Context) ([]StatusTag, error) {
	rows, err := q.db.Query(ctx, listStatusTags)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []StatusTag{}
	for rows.Next() {
		var i StatusTag
		if err := rows.Scan(&i.StatusID, &i.Status); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
