// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.22.0
// source: sqlc.account_past_works.sql

package repository

import (
	"context"
)

const createAccountPastWorks = `-- name: CreateAccountPastWorks :one
INSERT INTO account_past_works (opus, account_id)
VALUES ($1, $2)
RETURNING opus, account_id
`

type CreateAccountPastWorksParams struct {
	Opus      int32  `json:"opus"`
	AccountID string `json:"account_id"`
}

func (q *Queries) CreateAccountPastWorks(ctx context.Context, arg CreateAccountPastWorksParams) (AccountPastWork, error) {
	row := q.db.QueryRow(ctx, createAccountPastWorks, arg.Opus, arg.AccountID)
	var i AccountPastWork
	err := row.Scan(&i.Opus, &i.AccountID)
	return i, err
}

const deleteAccountPastWorksByOpus = `-- name: DeleteAccountPastWorksByOpus :exec
DELETE FROM account_past_works
WHERE opus = $1
`

func (q *Queries) DeleteAccountPastWorksByOpus(ctx context.Context, opus int32) error {
	_, err := q.db.Exec(ctx, deleteAccountPastWorksByOpus, opus)
	return err
}

const listAccountPastWorksByOpus = `-- name: ListAccountPastWorksByOpus :many
SELECT opus, account_id
FROM account_past_works
WHERE opus = $1
`

func (q *Queries) ListAccountPastWorksByOpus(ctx context.Context, opus int32) ([]AccountPastWork, error) {
	rows, err := q.db.Query(ctx, listAccountPastWorksByOpus, opus)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AccountPastWork{}
	for rows.Next() {
		var i AccountPastWork
		if err := rows.Scan(&i.Opus, &i.AccountID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
