// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.19.1
// source: hackathonStatusTags.sql

package repository

import (
	"context"
)

const createHackathonStatusTag = `-- name: CreateHackathonStatusTag :one
INSERT INTO hackathon_status_tags (
    hackathon_id,
    status_id
  )VALUES(
    $1,
    $2
  )
RETURNING hackathon_id, status_id
`

type CreateHackathonStatusTagParams struct {
	HackathonID int32 `json:"hackathon_id"`
	StatusID    int32 `json:"status_id"`
}

func (q *Queries) CreateHackathonStatusTag(ctx context.Context, arg CreateHackathonStatusTagParams) (HackathonStatusTag, error) {
	row := q.db.QueryRowContext(ctx, createHackathonStatusTag, arg.HackathonID, arg.StatusID)
	var i HackathonStatusTag
	err := row.Scan(&i.HackathonID, &i.StatusID)
	return i, err
}

const deleteHackathonStatusTagsByHackathonID = `-- name: DeleteHackathonStatusTagsByHackathonID :exec
DELETE FROM hackathon_status_tags WHERE hackathon_id = $1
`

func (q *Queries) DeleteHackathonStatusTagsByHackathonID(ctx context.Context, hackathonID int32) error {
	_, err := q.db.ExecContext(ctx, deleteHackathonStatusTagsByHackathonID, hackathonID)
	return err
}

const getHackathonStatusTagsByHackathonID = `-- name: GetHackathonStatusTagsByHackathonID :many
SELECT hackathon_id, status_id
FROM hackathon_status_tags
WHERE hackathon_id = $1
`

func (q *Queries) GetHackathonStatusTagsByHackathonID(ctx context.Context, hackathonID int32) ([]HackathonStatusTag, error) {
	rows, err := q.db.QueryContext(ctx, getHackathonStatusTagsByHackathonID, hackathonID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []HackathonStatusTag{}
	for rows.Next() {
		var i HackathonStatusTag
		if err := rows.Scan(&i.HackathonID, &i.StatusID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
