// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "https://hc-dev.seafood-dev.com",
        "contact": {
            "name": "murasame29",
            "url": "https://twitter.com/fresh_salmon256",
            "email": "oogiriminister@gmail.com"
        },
        "license": {
            "name": "No-license"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/status_tags": {
            "get": {
                "description": "Get all StatusTag",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "StatusTag"
                ],
                "summary": "Get all StatusTag",
                "responses": {
                    "200": {
                        "description": "success response",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/response.StatusTag"
                            }
                        }
                    },
                    "400": {
                        "description": "error response"
                    },
                    "500": {
                        "description": "error response"
                    }
                }
            },
            "post": {
                "description": "Create a new StatusTag",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "StatusTag"
                ],
                "summary": "Create a new StatusTag",
                "parameters": [
                    {
                        "description": "request body",
                        "name": "CreateStatusTagRequest",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.CreateStatusTag"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "success response",
                        "schema": {
                            "$ref": "#/definitions/response.StatusTag"
                        }
                    },
                    "400": {
                        "description": "error response"
                    },
                    "500": {
                        "description": "error response"
                    }
                }
            }
        },
        "/status_tags/{id}": {
            "get": {
                "description": "Get StatusTag by id",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "StatusTag"
                ],
                "summary": "Get StatusTag by id",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "status tag id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "request body",
                        "name": "CreateStatusTagRequest",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.GetStatusTagByID"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "success response",
                        "schema": {
                            "$ref": "#/definitions/response.StatusTag"
                        }
                    },
                    "400": {
                        "description": "error response"
                    },
                    "500": {
                        "description": "error response"
                    }
                }
            },
            "put": {
                "description": "Update StatusTag by id",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "StatusTag"
                ],
                "summary": "Update StatusTag by id",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "status tag id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "request body",
                        "name": "CreateStatusTagRequest",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.UpdateStatusTag"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "success response",
                        "schema": {
                            "$ref": "#/definitions/response.StatusTag"
                        }
                    },
                    "400": {
                        "description": "error response"
                    },
                    "500": {
                        "description": "error response"
                    }
                }
            }
        }
    },
    "definitions": {
        "request.CreateStatusTag": {
            "type": "object",
            "properties": {
                "status": {
                    "type": "string"
                }
            }
        },
        "request.GetStatusTagByID": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                }
            }
        },
        "request.UpdateStatusTag": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "response.StatusTag": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "status": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "0.1.0",
	Host:             "https://hc-dev.seafood-dev.com",
	BasePath:         "/v1",
	Schemes:          []string{},
	Title:            "Hack-Portal Backend API",
	Description:      "Hack-Portal Backend API serice",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
