-- 制約削除
ALTER TABLE "accounts" DROP CONSTRAINT "accounts_locate_id_fkey";
ALTER TABLE "account_tags" DROP CONSTRAINT "account_tags_user_id_fkey";
ALTER TABLE "account_tags" DROP CONSTRAINT "account_tags_tech_tag_id_fkey";
ALTER TABLE "past_work_tags" DROP CONSTRAINT "past_work_tags_tech_tag_id_fkey";
ALTER TABLE "past_work_tags" DROP CONSTRAINT "past_work_tags_opus_fkey";
ALTER TABLE "account_past_works" DROP CONSTRAINT "account_past_works_user_id_fkey";
ALTER TABLE "account_past_works" DROP CONSTRAINT "account_past_works_opus_fkey";
ALTER TABLE "rate_entries" DROP CONSTRAINT "rate_entries_user_id_fkey";
ALTER TABLE "follows" DROP CONSTRAINT "follows_to_user_id_fkey";
ALTER TABLE "follows" DROP CONSTRAINT "follows_from_user_id_fkey";
ALTER TABLE "hackathons_data" DROP CONSTRAINT "hackathons_data_opus_fkey";
ALTER TABLE "hackathons_data" DROP CONSTRAINT "hackathons_data_award_id_fkey";
ALTER TABLE "hackathons_data" DROP CONSTRAINT "hackathons_data_hackathon_id_fkey";
ALTER TABLE "hackathon_status_tags" DROP CONSTRAINT "hackathon_status_tags_hackathon_id_fkey";
ALTER TABLE "hackathon_status_tags" DROP CONSTRAINT "hackathon_status_tags_status_id_fkey";
ALTER TABLE "bookmarks" DROP CONSTRAINT "bookmarks_hackathon_id_fkey";
ALTER TABLE "bookmarks" DROP CONSTRAINT "bookmarks_user_id_fkey";
ALTER TABLE "rooms" DROP CONSTRAINT "rooms_hackathon_id_fkey";
ALTER TABLE "rooms_accounts" DROP CONSTRAINT "rooms_accounts_room_id_fkey";
ALTER TABLE "rooms_accounts" DROP CONSTRAINT "rooms_accounts_user_id_fkey";
ALTER TABLE "past_work_frameworks" DROP CONSTRAINT "past_work_frameworks_framework_id_fkey";
ALTER TABLE "frameworks" DROP CONSTRAINT "frameworks_tech_tag_id_fkey";
ALTER TABLE "past_work_frameworks" DROP CONSTRAINT "past_work_frameworks_opus_fkey";
ALTER TABLE "account_frameworks" DROP CONSTRAINT "account_frameworks_account_id_fkey";
ALTER TABLE "account_frameworks" DROP CONSTRAINT "account_frameworks_framework_id_fkey";

-- テーブル削除
DROP TABLE IF EXISTS "hackathons_data";
DROP TABLE IF EXISTS "awards";
DROP TABLE IF EXISTS "rooms_accounts";
DROP TABLE IF EXISTS "follows";
DROP TABLE IF EXISTS "account_past_works";
DROP TABLE IF EXISTS "bookmarks";
DROP TABLE IF EXISTS "hackathon_status_tags";
DROP TABLE IF EXISTS "rate_entries";
DROP TABLE IF EXISTS "past_work_tags";
DROP TABLE IF EXISTS "account_tags";
DROP TABLE IF EXISTS "tech_tags";
DROP TABLE IF EXISTS "frameworks";
DROP TABLE IF EXISTS "past_work_frameworks";
DROP TABLE IF EXISTS "account_frameworks";
DROP TABLE IF EXISTS "status_tags";
DROP TABLE IF EXISTS "past_works";
DROP TABLE IF EXISTS "accounts";
DROP TABLE IF EXISTS "users";
DROP TABLE IF EXISTS "locates";
DROP TABLE IF EXISTS "rooms";
DROP TABLE IF EXISTS "hackathons";